### ISSUE TITLE
Improve Error Messages On Mandatory Solution Configuration

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/engine#1365]
## Expected Behavior

create a new solution from the `base` patterns repository: 
```sh
# create solution with base cookiecutter pattern
mkdir ./mynewsolution
cd mynewsolution
cookiecutter /opt/hamlet/patterns/products/base`

# Navigate into segment directory of new solution and have hamlet create a unitlist just to verify that the thing works
cd mynewsolution/config/solutionsv2/environment/segment

# assign an Account to use (assuming correct directory structure here)
export ACCOUNT=purplehippo01

# perform a minimal engine task against the solution to verify that the thing works (expecting no output)
hamlet create unitlist
```

## Current Behavior

the hamlet cli command can fail due to unspecified mandatory minimum configuration within the combined CMDB's. The errors are unhelpful to hamlet end-users.

```sh
----
FTL stack trace ("~" means nesting-related):
        - Failed at: #function addIdNameToObject(entity, d...  [in template "common.ftl" in function "addIdNameToObject" at line 1145, column 1]
        - Reached through: #include "setContext.ftl"  [in template "bootstrap.ftl" at line 77, column 1]
        - Reached through: #include "/bootstrap.ftl"  [in template "createUnitlist.ftl" at line 2, column 1]
----

Java stack trace (for programmers):
----
freemarker.core._MiscTemplateException: [... Exception message was already printed; see it above ...]
        at freemarker.core.Macro$Context.checkParamsSetAndApplyDefaults(Macro.java:308)
        at freemarker.core.Environment.invokeMacroOrFunctionCommonPart(Environment.java:875)
        at freemarker.core.Environment.invokeMacro(Environment.java:812)
        at freemarker.core.Environment.invokeFunction(Environment.java:828)
        at freemarker.core.MethodCall._eval(MethodCall.java:65)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.Assignment.accept(Assignment.java:134)
        at freemarker.core.Environment.visit(Environment.java:334)
        at freemarker.core.Environment.visit(Environment.java:340)
        at freemarker.core.Environment.visit(Environment.java:340)
        at freemarker.core.Environment.visit(Environment.java:340)
        at freemarker.core.Environment.include(Environment.java:2925)
        at freemarker.core.Include.accept(Include.java:171)
        at freemarker.core.Environment.visit(Environment.java:334)
        at freemarker.core.Environment.visit(Environment.java:340)
        at freemarker.core.Environment.include(Environment.java:2925)
        at freemarker.core.Include.accept(Include.java:171)
        at freemarker.core.Environment.visit(Environment.java:334)
        at freemarker.core.Environment.visit(Environment.java:340)
        at freemarker.core.Environment.process(Environment.java:313)
        at freemarker.template.Template.process(Template.java:383)
        at io.codeontap.freemarkerwrapper.RunFreeMarker.main(RunFreeMarker.java:294)

Exception in thread "main" FreeMarker template error:
When calling function "addIdNameToObject", required parameter "entity" (parameter #1) was specified, but had null/missing value.
```

## Possible Solution

wrap each of the mandatory configuration options with an `if...?has_content` directive with a Fatal log macro on false, and provide helpful information to the end user.

## Steps to Reproduce (for bugs)
(see above)

## Context

First time users are somewhat likely to have a misconfiguration or two right out of the gate. Error messages should provide enough context to guide the user back on track.

## Your Environment

* CMDB Version used: 
Direct from the base cookiecutter pattern:
{
  "Version": {
    "Upgrade": "v1.3.2",
    "Cleanup": "v1.1.1"
  }
}

* Blueprint:

**Comment by roleyfoley** [comment]
We should test this again and flesh out some more issues that need to be fiex

**Comment by RossMurr4y** [comment]
I have just tested the generation of a test tenant, account and product and performed a **query**, **unit list generation**, **listing of deployments** and **baseline template generation** against them and was successful, even when using an undefined environment name such as `doesntexist`. 

I believe that was the original cause for this ticket, as at the time the environment I was attempting to use had not been defined anywhere and it was complicated to track down.

Certainly happy to call this ticket closed, new issues that arise should receive individual tickets.

```bash
#### Generating the Tenant
hamlet @ ~/cmdb/cmdb/gs/testing
└─ $ hamlet generate cmdb tenant --prompt
Enter tenant id: exampletenant
Enter tenant name [exampletenant]: 
Enter domain stem []: exampletenant.com.au
Enter default region [ap-southeast-2]: 
Enter audit log expiry days [2555]: 
Enter audit log offline days [90]: 
+-----+------------------------+----------------------+
|   № | parameter              | value                |
|-----+------------------------+----------------------|
|   1 | tenant id              | exampletenant        |
|   2 | tenant name            | exampletenant        |
|   3 | domain stem            | exampletenant.com.au |
|   4 | default region         | ap-southeast-2       |
|   5 | audit log expiry days  | 2555                 |
|   6 | audit log offline days | 90                   |
+-----+------------------------+----------------------+
Is everything correct? [y/N]: y

#### Generating the Account
hamlet @ ~/cmdb/cmdb/gs/testing
└─ $ hamlet generate cmdb account --prompt
Enter account id: exacct01
Enter account name [exacct01]: 
Enter account seed [7emod18h43]: 
Enter account type [aws]: 
Enter aws account id []: 1234567890
+-----+----------------+------------+
|   № | parameter      | value      |
|-----+----------------+------------|
|   1 | account id     | exacct01   |
|   2 | account name   | exacct01   |
|   3 | account seed   | 7emod18h43 |
|   4 | account type   | aws        |
|   5 | aws account id | 1234567890 |
+-----+----------------+------------+
Is everything correct? [y/N]: y

#### Generating the product
hamlet @ ~/cmdb/cmdb/gs/testing
└─ $ hamlet generate product base --prompt
Enter product id: fidgetyclicks
Enter product name [fidgetyclicks]: 
Enter domain id []: fidgety
Enter solution id: fiddlesticks
Enter solution name [fiddlesticks]: 
Enter environment id: integration
Enter environment name [integration]: 
Enter segment id [default]: 
Enter segment name [default]: 
+-----+------------------+---------------+
|   № | parameter        | value         |
|-----+------------------+---------------|
|   1 | product id       | fidgetyclicks |
|   2 | product name     | fidgetyclicks |
|   3 | domain id        | fidgety       |
|   4 | solution id      | fiddlesticks  |
|   5 | solution name    | fiddlesticks  |
|   6 | environment id   | integration   |
|   7 | environment name | integration   |
|   8 | segment id       | default       |
|   9 | segment name     | default       |
+-----+------------------+---------------+
Is everything correct? [y/N]: y


#### Navigate to the Segment
hamlet @ ~/cmdb/cmdb/gs/testing
└─ $ cd fidgetyclicks/config/solutionsv2/integration/default/

#### Set the Account
hamlet @ ~/cmdb/cmdb/gs/testing/fidgetyclicks/config/solutionsv2/integration/default
└─ $ export ACCOUNT=exacct01

#### Run a Query
hamlet @ ~/cmdb/cmdb/gs/testing/fidgetyclicks/config/solutionsv2/integration/default
└─ $ hamlet query -r list tiers
╒════╤══════╤════════════╤═══════════════════════════════════════════════════════════════════════╤═══════════════════════╕
│    │ Id   │ Name       │ Description                                                           │ NetworkEnabledState   │
╞════╪══════╪════════════╪═══════════════════════════════════════════════════════════════════════╪═══════════════════════╡
│  0 │ mgmt │ management │ Supports ssh based host access and internet access for internal hosts │ True                  │
├────┼──────┼────────────┼───────────────────────────────────────────────────────────────────────┼───────────────────────┤
│  1 │ gbl  │ global     │ Components which are used for Global Services                         │ False                 │

#### Generate a Unitlist
└─ $ hamlet entrance invoke-entrance -e unitlist
(Info) Generating generationcontract file ...

(Info) Generating documents from generation contract /tmp/cot_aQwoIy/create_template_dswM90/create_template_CRwWaX/results/unitlist-generation-contract.json
(Info) Generating managementcontract file ...

(Info) Differences detected ...
(Info) ... updating unitlist-generation-contract.json ...
(Info) ... updating unitlist-managementcontract.json ...

#### List Deployments
hamlet @ ~/cmdb/cmdb/gs/testing/fidgetyclicks/config/solutionsv2/integration/default
└─ $ hamlet deploy list-deployments
| DeploymentGroup   | DeploymentUnit   | DeploymentProvider   |
|-------------------|------------------|----------------------|
| segment           | baseline         | aws                  |
| segment           | iam              | aws                  |
| segment           | lg               | aws                  |
| segment           | eip              | aws                  |
| segment           | s3               | aws                  |
| segment           | cmk              | aws                  |
| segment           | vpc              | aws                  |
| segment           | igw              | aws                  |
| segment           | vpcendpoint      | aws                  |
| segment           | nat              | aws                  |
| segment           | ssh              | aws                  |
| solution          | eip              | aws                  |
| solution          | iam              | aws                  |
| solution          | lg               | aws                  |
| solution          | cwlogsdatafeed   | aws                  |
| application       | iam              | aws                  |
| application       | lg               | aws                  |
| application       | cwlogslambda     | aws                  |
```

```bash
hamlet @ ~/cmdb/cmdb/gs/testing
└─ $ hamlet generate product base --prompt
Enter product id: wysiwygoptics
Enter product name [wysiwygoptics]: 
Enter domain id []: optics.com.au
Enter solution id: wysiwyg
Enter solution name [wysiwyg]: 
Enter environment id: doesntexist
Enter environment name [doesntexist]: 
Enter segment id [default]: 
Enter segment name [default]: 
+-----+------------------+---------------+
|   № | parameter        | value         |
|-----+------------------+---------------|
|   1 | product id       | wysiwygoptics |
|   2 | product name     | wysiwygoptics |
|   3 | domain id        | optics.com.au |
|   4 | solution id      | wysiwyg       |
|   5 | solution name    | wysiwyg       |
|   6 | environment id   | doesntexist   |
|   7 | environment name | doesntexist   |
|   8 | segment id       | default       |
|   9 | segment name     | default       |
+-----+------------------+---------------+
Is everything correct? [y/N]: y

hamlet @ ~/cmdb/cmdb/gs/testing
└─ $ cd wysiwygoptics/config/solutionsv2/doesntexist/default/

hamlet @ ~/cmdb/cmdb/gs/testing/wysiwygoptics/config/solutionsv2/doesntexist/default
└─ $ export ACCOUNT=exacct01

hamlet @ ~/cmdb/cmdb/gs/testing/wysiwygoptics/config/solutionsv2/doesntexist/default
└─ $ hamlet query -r list tiers
╒════╤══════╤════════════╤═══════════════════════════════════════════════════════════════════════╤═══════════════════════╕
│    │ Id   │ Name       │ Description                                                           │ NetworkEnabledState   │
╞════╪══════╪════════════╪═══════════════════════════════════════════════════════════════════════╪═══════════════════════╡
│  0 │ mgmt │ management │ Supports ssh based host access and internet access for internal hosts │ True                  │
├────┼──────┼────────────┼───────────────────────────────────────────────────────────────────────┼───────────────────────┤
│  1 │ gbl  │ global     │ Components which are used for Global Services                         │ False                 │
╘════╧══════╧════════════╧═══════════════════════════════════════════════════════════════════════╧═══════════════════════╛

hamlet @ ~/cmdb/cmdb/gs/testing/wysiwygoptics/config/solutionsv2/doesntexist/default
└─ $ hamlet entrance invoke-entrance -e unitlist
(Info) Generating generationcontract file ...
(Info) Generating documents from generation contract /tmp/cot_QZxN5R/create_template_1wwrOQ/create_template_f8GpNH/results/unitlist-generation-contract.json
(Info) Generating managementcontract file ...
(Info) Differences detected ...
(Info) ... updating unitlist-generation-contract.json ...
(Info) ... updating unitlist-managementcontract.json ...
(Info) Generating generationcontract file ...
(Info) Generating documents from generation contract /tmp/cot_ZcR1pr/create_template_mLNfY8/create_template_q5UbUi/results/seg-baseline-exacct01-ap-southeast-2-generation-contract.json
(Info) Generating prologue file ...
(Info) Generating template file ...
(Info) Generating epilogue file ...
(Info) Differences detected ...
(Info) ... updating seg-baseline-exacct01-ap-southeast-2-generation-contract.json ...
(Info) ... updating seg-baseline-exacct01-ap-southeast-2-prologue.sh ...
(Info) ... updating seg-baseline-exacct01-ap-southeast-2-template.json ...
(Info) ... updating seg-baseline-exacct01-ap-southeast-2-epilogue.sh ...
```
