### ISSUE TITLE
[BUG] CLI exceptions when installing tram-20220311

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine#1959]
## Current Behaviour
Local run of hamletio/hamlet:latest-jenkins
```
docker run -it a71187c12278 /bin/bash

jenkins@2e36d19b7f12:~$ export HAMLET_ENGINE=tram-20220311
jenkins@2e36d19b7f12:~$ hamlet engine install-engine --update tram-20220311
Traceback (most recent call last):
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/backend/engine/__init__.py", line 127, in get_engine
    result = [
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/config.py", line 293, in set_engine
    self._engine = self.engine_store.get_engine(
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/backend/engine/__init__.py", line 133, in get_engine
    raise EngineStoreMissingEngineException(
hamlet.backend.engine.exceptions.EngineStoreMissingEngineException: [!] Could not find the requested engine
[!] - name: tram-20220311
[!] - locations: ['installed']
[!] Run hamlet engine list-engines to find the engine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/backend/engine/__init__.py", line 127, in get_engine
    result = [
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.pyenv/versions/3.9.10/bin/hamlet", line 8, in <module>
    sys.exit(command.root())
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/decorators.py", line 64, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/decorators.py", line 208, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/decorators.py", line 103, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/decorators.py", line 162, in wrapper
    opts.set_engine(kwargs.pop("engine"), kwargs.pop("engine_search_locations"))
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/config.py", line 299, in set_engine
    self.engine_store.get_engine(engine_name, locations=locations).install()
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/backend/engine/__init__.py", line 133, in get_engine
    raise EngineStoreMissingEngineException(
hamlet.backend.engine.exceptions.EngineStoreMissingEngineException: [!] Could not find the requested engine
[!] - name: tram-20220311
[!] - locations: ('installed', 'local', 'remote')
[!] Run hamlet engine list-engines to find the engine
jenkins@2e36d19b7f12:~$ hamlet engine install-engine tram-20220311
Traceback (most recent call last):
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/backend/engine/__init__.py", line 127, in get_engine
    result = [
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/config.py", line 293, in set_engine
    self._engine = self.engine_store.get_engine(
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/backend/engine/__init__.py", line 133, in get_engine
    raise EngineStoreMissingEngineException(
hamlet.backend.engine.exceptions.EngineStoreMissingEngineException: [!] Could not find the requested engine
[!] - name: tram-20220311
[!] - locations: ['installed']
[!] Run hamlet engine list-engines to find the engine

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/backend/engine/__init__.py", line 127, in get_engine
    result = [
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.pyenv/versions/3.9.10/bin/hamlet", line 8, in <module>
    sys.exit(command.root())
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/decorators.py", line 64, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/decorators.py", line 208, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/decorators.py", line 103, in wrapper
    return ctx.invoke(func, *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/decorators.py", line 162, in wrapper
    opts.set_engine(kwargs.pop("engine"), kwargs.pop("engine_search_locations"))
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/command/common/config.py", line 299, in set_engine
    self.engine_store.get_engine(engine_name, locations=locations).install()
  File "/home/jenkins/.pyenv/versions/3.9.10/lib/python3.9/site-packages/hamlet/backend/engine/__init__.py", line 133, in get_engine
    raise EngineStoreMissingEngineException(
hamlet.backend.engine.exceptions.EngineStoreMissingEngineException: [!] Could not find the requested engine
[!] - name: tram-20220311
[!] - locations: ('installed', 'local', 'remote')
[!] Run hamlet engine list-engines to find the engine```

## Expected Behaviour
Engine installs correctly

## Possible Solution
<!-- If you have one, suggest a fix/reason for the bug -->

## Steps to Reproduce
1. download jenkins container
2. run a shell in it
3. define HAMLET_ENGINE
4. attempt to update a previously uninstalled tram version

NOTE: if HAMLET_ENGINE is not set, install works correctly.

## Your Environment
* hamlet 9.17.0

<!-- please ensure you redact any secure or personally identifying information -->
<!-- Include as many relevant details about the environment you experienced the bug in -->

**Comment by roleyfoley** [comment]
Seems to be ok in the standard releases and we have been through a few since then.
